name: CI

on:
  push:
    branches: [main]

jobs:
  fastapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
      - uses: actions/checkout@v4.1.7
        
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{secrets.USER}}
          password: ${{secrets.PASSWD}}

      - name: Instalar SonarQube Scanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner-cli-4.6.2.2472-linux.zip -d $HOME
              export PATH="$HOME/sonar-scanner-4.6.2.2472-linux/bin:$PATH"

      - name: Configurar SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Rodar Análise SonarQube
        run: |
          sonar-scanner \
              -Dsonar.projectKey=nome-do-projeto \
              -Dsonar.sources=. \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.login=$SONAR_TOKEN

      - name: Verificar Qualidade do Código
        run: |
          if [ "$(curl -s $SONAR_HOST_URL/api/qualitygates/project_status?projectKey=nome-do-projeto | jq -r .projectStatus.status)" != "OK" ]; then
            echo "Qualidade do código não passou nos critérios definidos."
              exit 1
          fi
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          push: true
          tags: |
            edwardaojopi/minha-api-fastapi-1:v1
            edwardaojopi/minha-api-fastapi-1:latest

      - name: Instalar Trivy
        run: |
          sudo apt-get update && sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/download/v0.34.0/trivy_0.34.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.34.0_Linux-64bit.deb

      - name: Escanear a Imagem com Trivy
        run: |
          trivy image --severity HIGH,CRITICAL nome-da-imagem

      - name: Processar Resultados
        if: failure()
        run: |
          echo "Vulnerabilidades encontradas. Revisar os resultados do Trivy."
          exit 1

      - name: Push da Imagem (se a verificação passar)
        if: success()
        run: docker push nome-da-imagem
